version: '3.9'
name: "elysium"
services:
  caracal.elysium.services:
    image: ${DOCKER_REGISTRY-}caracal_elysium_services
    deploy:
      resources:
        limits:
          memory: 200M
    mem_reservation: 200M
    build:
      context: ..
      dockerfile: ./src/interfaces/Caracal.Elysium.Services/Dockerfile
      args:
        - PASSWORD_ENV_SEEDED=${PASSWORD_ENV_SEEDED}
    environment:
      - PASSWORD_ENV_SEEDED=password1
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+;http://+:5000
      - ASPNETCORE_ENVIRONMENT=Release
  
  hivemq-server:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq-server
    deploy:
      resources:
        limits:
          memory: 800M
    mem_reservation: 800M
    ports:
      - "1883:1883"
      - "8081:8080"
      - "8883:8883"
      - "9399:9399"
    volumes:
      - ./hivemq/server/conf:/opt/hivemq/conf
      - ./hivemq/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
      - ../build/certs/hivemq/certs/default:/certs
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"

  hivemq-cloud:
    container_name: hivemq-cloud
    image: hivemq/hivemq-ce:latest
    deploy:
      resources:
        limits:
          memory: 800M
    mem_reservation: 800M
    ports:
      - "1884:1883"
      - "8084:8080"
      - "2884:8883"
    volumes:
      - ./hivemq/cloud/conf:/opt/hivemq/conf
      - ./hivemq/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
      - ../build/certs/hivemq/certs/cloud:/certs
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"